name: CodeProject.AI Server (GPU)
version: "2.1.9"
url: https://github.com/codeproject/CodeProject.AI-Server
slug: codeproject-ai-gpu
description: "CodeProject Server is a self contained service that software developers can include in, and distribute with, their applications in order to augment their apps with the power of AI."
arch:
  - amd64
startup: application
boot: auto
webui: http://[HOST]:[PORT:32168]
watchdog: "http://[HOST]:[PORT:32168]/"
ingress: true
ingress_port: 32168
ingress_entry: /
panel_admin: false
panel_icon: "mdi:robot"
panel_title: CodeProject.AI
ports:
  32168/tcp: 32168
ports_description:
  32168/tcp: "Port of your CodeProject.AI server"
environment:
  VISION-FACE: "true"
  VISION-DETECTION: "true"
  VISION-SCENE: "true"
  MODELSTORE-DETECTION: "true"
  TZ: ""
image: ghcr.io/judahrand/hassio-addon-codeproject-ai/codeproject-ai-gpu-{arch}
video: True
