name: CodeProject.AI Server (CPU)
version: "2.1.9"
url: https://github.com/codeproject/CodeProject.AI-Server
slug: codeproject-ai-cpu
description: "CodeProject Server is a self contained service that software developers can include in, and distribute with, their applications in order to augment their apps with the power of AI."
arch:
  - amd64
  - aarch64
startup: application
boot: auto
webui: http://[HOST]:[PORT:5000]
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
panel_icon: "mdi:robot"
panel_title: CodeProject.AI
ports:
  5000/tcp: null
ports_description:
  5000/tcp: "Port of your CodeProject.AI server"
environment:
  VISION-FACE: "true"
  VISION-DETECTION: "true"
  VISION-SCENE: "true"
  MODELSTORE-DETECTION: "true"
  TZ: ""
image: ghcr.io/judahrand/hassio-addon-codeproject-ai/codeproject-ai-cpu-{arch}
