name: Release

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io/judahrand/hassio-addon-codeproject-ai

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        addon-folder:
          - codeproject-ai-rpi
          - codeproject-ai-gpu
          - codeproject-ai-cpu
        arch:
          - amd64
          - aarch64
        exclude:
          - addon-folder: codeproject-ai-gpu
            arch: aarch64
          - addon-folder: codeproject-ai-rpi
            arch: amd64
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target ${{ matrix.addon-folder }}
